name: Update Fire Data

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allows you to run it manually button click

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download NSW Data
        run: curl "https://www.rfs.nsw.gov.au/feeds/majorIncidents.json" -o nsw_data.json

      - name: Download VIC Data
        run: curl "https://emergency.vic.gov.au/public/osom-geojson.json" -o vic_data.json

      - name: Commit and Push changes
        run: |
          git config --global user.name 'FireMapBot'
          git config --global user.email 'bot@noreply.github.com'
          git add nsw_data.json vic_data.json
          git commit -m "Auto-update fire data" || exit 0
          git push
